#!/bin/ksh

set -eu

usage() {
	echo "usage: robsd-clean count" 1>&2
	exit 1
}

. "${EXECDIR:-/usr/local/libexec/robsd}/util.sh"

[ $# -ne 1 ] && usage

setprogname "robsd-clean"
[ "$(id -u)" -ne 0 ] && fatal "must be run as root"
config_load "${ROBSDRC:-/etc/robsdrc}"

purge "$BUILDDIR" "$1" | while read -r _d; do
	info "moving ${_d} to the attic"
done
