#!/bin/ksh

set -eu

usage() {
	echo "usage: robsd-rescue" 1>&2
	exit 1
}

# last_release
last_release() {
	find "$ROBSDDIR" -type d -mindepth 1 -maxdepth 1 |
	grep -v -e "${ROBSDDIR}/attic" |
	sort -nr |
	head -1
}

. "${EXECDIR:-/usr/local/libexec/robsd}/util.sh"

[ $# -ne 0 ] && usage

setprogname "robsd-rescue"
[ "$(id -u)" -ne 0 ] && fatal "must be run as root"
config_load "${ROBSDCONF:-/etc/robsd.conf}"

LOGDIR="$(last_release)"
if [ -z "$LOGDIR" ]; then
	fatal "release directory not found"
else
	info "using release directory ${LOGDIR}"
fi

if step_eval -n patch "${LOGDIR}/steps" 2>/dev/null; then
	# shellcheck disable=SC2046
	diff_revert "$BSDSRCDIR" $(diff_list "$LOGDIR" "src.diff")
	# shellcheck disable=SC2046
	diff_revert "$XSRCDIR" $(diff_list "$LOGDIR" "xenocara.diff")
else
	info "step patch not found, cannot revert diff(s)"
fi

if lock_release "$ROBSDDIR" "$LOGDIR"; then
	info "released lock"
fi
