.Dd $Mdocdate: November 27 2018$
.Dt ROBSD 8
.Os
.Sh NAME
.Nm robsd
.Nd build OpenBSD release
.Sh SYNOPSIS
.Nm robsd
.Op Fl v
.Op Fl S Ar src-diff
.Op Fl X Ar xenocara-diff
.Nm
.Op Fl v
.Fl r Ar path
.Sh DESCRIPTION
The
.Nm
utility builds a
.Ox
release according to
.Xr release 8
process.
In addition, some auxiliary stages are also executed:
.Bl -dash
.It
After stage 2
.Pq Build and install a new kernel
the machine is rebooted.
Upon the next boot, the same release build is resumed from
.Xr rc.firsttime 8 .
.It
After stage 8
.Pq Create boot and installation disk images
the final release files are distributed to another host using
.Xr rsync 1 .
.El
.Pp
Each release build is identified by a directory created by
.Nm
rooted in
.Ev BUILDDIR
and is named after the current date.
The release directory contains the entries as follows.
In addition, each executed stage has a corresponding log file in the same
directory.
.Bl -tag -width "report"
.It reldir
Directory containing the final release files.
Referred to as RELEASEDIR in
.Xr release 8 .
.It report
A summary of the release build which is delivered as a mail to the user who
started the release build once
.Nm
terminates.
If the same user is not in the wheel group, root will also receive a copy of
the report.
.It stages
Internal representation of executed stages so far for the current release
build.
This file should never be edited manually.
.El
.Pp
.Nm
must be run as root.
However, some stages can operate on behalf of another user using
.Xr su 1 ,
see
.Sx ENVIRONMENT .
.Pp
The options are as follows:
.Bl -tag -width "-X xenocara-diff"
.It Fl r Ar path
Resume a release build located at
.Ar path .
If the last executed stage failed, it will be executed again.
Otherwise, the next stage will be executed.
.It Fl S Ar src-diff
Diff to apply to the src tree.
The same diff will be reverted once the release is finished.
In addition, a copy of the diff is saved to a file named
.Pa src.diff
in the release directory.
.It Fl v
Enable verbose output.
.It Fl X Ar xenocara-diff
Diff to apply to the xenocara tree.
The same diff will be reverted once the release is finished.
In addition, a copy of the diff is saved to a file named
.Pa xenocara.diff
in the release directory.
.El
.Sh ENVIRONMENT
The
.Nm
utility is configured using environment variables.
Variables are inherited from the current environment and can optionally be
specified in
.Pa /etc/robsdrc ,
which is sourced during runtime.
Where the latter takes higher precedence.
.Pp
The following variables are recognized.
Default values are displayed in brackets.
.Bl -tag -width BSDOBJDIR
.It Ev BSDOBJDIR
Object directory for the src tree.
.Bq Pa /usr/obj
.It Ev BSDSRCDIR
Source directory for the src tree.
.Bq Pa /usr/src
.It Ev BUILDDIR
Directory to store releases.
.It Ev CVSROOT
Upstream
.Xr cvs 1
repository used to update sources from.
.It Ev CVSUSER
User to perform
.Xr cvs 1
and
.Xr patch 1
operations on behalf of.
.It Ev DESTDIR
Directory rooted on a filesystem mounted with the
.Em noperm
.Xr mount 8
option, see
.Xr release 8 .
.It Ev DISTRIBHOST
Host to upload the final release files to during the distribution stage.
.It Ev DISTRIBPATH
Directory on
.Ev DISTRIBHOST
to upload the final release files to during the distribution stage.
.It Ev DISTRIBUSER
User to perform
.Xr rsync 1
operations on behalf of.
.It Ev KEEP
Number of releases to keep in
.Ev BUILDDIR .
Defaults to keeping all releases.
.Bq 0
.Pp
Old releases are moved to a directory named
.Pa attic
rooted in
.Ev BUILDDIR .
Only the following files are kept for old releases in order to reduce disk
usage:
.Pa report ,
.Pa stages ,
.Pa src.diff ,
.Pa xenocara.diff ,
.Pa cvs.log
and the log from the last failing stage.
Those files can be used to track various metrics over time.
.It Ev SIGNIFY
Private key used to optionally sign the final release files using
.Xr signify 1 .
.It Ev X11OBJDIR
Object directory for the xenocara tree.
.Bq /usr/xobj
.It Ev X11SRCDIR
Source directory for the xenocara tree.
.Bq /usr/xenocara
.El
.Sh FILES
.Bl -tag -width "/etc/robsdrc"
.It Pa /etc/robsdrc
The default configuration file.
.El
.Sh EXAMPLES
Example
.Pa /etc/robsdrc
configuration file with all mandatory variables present:
.Bd -literal
BUILDDIR=/home/release
CVSROOT=anoncvs@anoncvs.eu.openbsd.org:/cvs
CVSUSER=anton
DESTDIR=/home/noperm
DISTRIBHOST=example.com
DISTRIBPATH=/var/www/pub/OpenBSD/snapshots/`machine`
DISTRIBUSER=anton
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr release 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
