#!/bin/ksh

set -eu

usage() {
	xargs 1>&2 <<-EOF
	usage: robsd-ports
	[-d]
	[-P ports-patch]
	[-c comment]
	[-r path]
	[-s step]
	[-t tag]
	EOF
	exit 1
}

. "${EXECDIR:-/usr/local/libexec/robsd}/util.sh"

setmode "robsd-ports"
setprogname "robsd-ports"
[ "$(id -u)" -ne 0 ] && fatal "must be run as root"

config_load <<'EOF'
ROBSDDIR="${robsddir}"
CHROOT="${chroot}"
KEEP="${keep}"
SKIP="${skip}"
PORTS="${ports}"
PORTSDIFF="${ports-diff}"
PORTSDIR="${ports-dir}"
EOF

_comment=""
_statpid=""
_step=1
_tags=""

while getopts "dP:c:r:s:t:" opt; do
	case "$opt" in
	d)	DETACH=0;;
	P)	PORTSDIFF="${PORTSDIFF} $(readlink -f "${OPTARG}")";;
	c)	_comment="$OPTARG";;
	r)	BUILDDIR="$(readlink -f "$OPTARG")";;
	s)	SKIP="${SKIP}${SKIP:+ }${OPTARG}";;
	t)	_tags="${_tags}${_tags:+ }${OPTARG}";;
	*)	usage;;
	esac
done
shift $((OPTIND - 1))
[ $# -ne 0 ] && usage

trap 'trap_exit -r "$ROBSDDIR" -b "$BUILDDIR" -s "$_statpid"' EXIT

if [ -z "$BUILDDIR" ]; then
	check_perf || exit 1

	BUILDDIR="${ROBSDDIR}/$(build_id "$ROBSDDIR")"
else
	_step="$(step_next "${BUILDDIR}/steps")"
fi
build_init "$BUILDDIR"
info "using directory ${BUILDDIR} at step ${_step}"

lock_acquire "$ROBSDDIR" "$BUILDDIR" || exit 1

if [ "$_step" -eq 1 ]; then
	if [ -n "$_comment" ]; then
		cat "$_comment" >"${BUILDDIR}/comment"
	elif [ -n "$PORTSDIFF" ]; then
		# Generate comment including a list of the diff(s).
		{
			echo 'Applied the following diff(s):'
			echo "$PORTSDIFF" | xargs ls
		} >"${BUILDDIR}/comment"
	fi

	# shellcheck disable=SC2086,SC2153
	diff_copy -d "${CHROOT}${PORTSDIR}" "${BUILDDIR}/ports.diff" $PORTSDIFF

	if [ -n "$SKIP" ]; then
		info "skipping steps: ${SKIP}"
		for _skip in $SKIP; do
			_id="$(step_id "$_skip")"
			step_end -S -n "$_skip" -s "$_id" "${BUILDDIR}/steps"
		done
	fi

	if [ -n "$_tags" ]; then
		echo "$_tags" >"${BUILDDIR}/tags"
	fi

	"$ROBSDSTAT" -H >"${BUILDDIR}/stat.csv"
fi

if [ "$KEEP" -gt 0 ]; then
	/usr/local/sbin/robsd-ports-clean "$KEEP"
fi

"$ROBSDSTAT" -u _pbuild -u _pfetch >>"${BUILDDIR}/stat.csv" &
_statpid="$!"

if [ "$DETACH" -eq 1 ]; then
	# Signal to info() that no further output should be written to robsd.log
	# as we're about redirect all output to the same log.
	DETACH=2
	exec </dev/null >>"${BUILDDIR}/robsd.log" 2>&1

	# Reinstall trap handler since they are not inherited by subprocesses.
	trap '-' EXIT
	{
		trap 'trap_exit -r "$ROBSDDIR" -b "$BUILDDIR" -s "${_statpid}"' EXIT
		robsd "$_step"
	} &
	info "running in detach mode as pid ${!}"
else
	info "running as pid ${$}"
	robsd "$_step"
fi
