.Dd $Mdocdate: October 14 2019$
.Dt ROBSD-CLEAN 8
.Os
.Sh NAME
.Nm robsd-clean ,
.Nm robsd-cross-clean ,
.Nm robsd-ports-clean ,
.Nm robsd-regress-clean
.Nd clean old invocations
.Sh SYNOPSIS
.Nm robsd-clean
.Ar count
.Nm robsd-cross-clean
.Ar count
.Nm robsd-ports-clean
.Ar count
.Nm robsd-regress-clean
.Ar count
.Sh DESCRIPTION
The
.Nm
utility cleans out old invocations,
keeping only the
.Ar count
number of latest ones.
.Pp
Old invocations are moved to a directory named
.Pa attic
rooted in
.Ic robsddir .
Only the following files are kept in order to reduce disk usage:
.Pa comment ,
.Pa env.log
.Pa rel/index.txt ,
.Pa report ,
.Pa stat.csv ,
.Pa step.csv ,
.Pa src.diff.*
and
.Pa xenocara.diff.* .
Those files can be used to track various metrics over time.
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr robsd 8 ,
.Xr robsd-cross 8 ,
.Xr robsd-ports 8 ,
.Xr robsd-regress 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
