#!/bin/ksh

set -eu

usage() {
	echo "usage: robsd-rescue" 1>&2
	exit 1
}

# last_release
last_release() {
	find "$ROBSDDIR" -type d -mindepth 1 -maxdepth 1 |
	grep -v -e "$KEEPDIR" |
	sort -nr |
	head -1
}

. "${EXECDIR:-/usr/local/libexec/robsd}/util.sh"

[ $# -ne 0 ] && usage

setmode "robsd"
setprogname "robsd-rescue"
[ "$(id -u)" -ne 0 ] && fatal "must be run as root"
config_load <<-'EOF'
ROBSDDIR="${robsddir}"
KEEPDIR="${keep-dir}"
BSDSRCDIR="${bsd-srcdir}"
CVSUSER="${cvs-user}"
EOF

BUILDDIR="$(last_release)"
if [ -z "$BUILDDIR" ]; then
	fatal "release directory not found"
else
	info "using release directory ${BUILDDIR}"
fi

if step_eval -n patch "${BUILDDIR}/steps" 2>/dev/null; then
	diff_list "$BUILDDIR" "src.diff" |
	while read -r _diff; do
		diff_revert -d "$BSDSRCDIR" -t "${BUILDDIR}/tmp" -u "$CVSUSER" "$_diff"
	done

	diff_list "$BUILDDIR" "xenocara.diff" |
	while read -r _diff; do
		diff_revert -d "$XSRCDIR" -t "${BUILDDIR}/tmp" -u "$CVSUSER" "$_diff"
	done
else
	info "step patch not found, cannot revert diff(s)"
fi

if lock_release "$ROBSDDIR" "$BUILDDIR"; then
	info "released lock"
fi
