.Dd $Mdocdate: February 11 2021$
.Dt ROBSD-REGRESSS 8
.Os
.Sh NAME
.Nm robsd-regress
.Nd run OpenBSD regression tests
.Sh SYNOPSIS
.Nm robsd-regress
.Op Fl D
.Op Fl c Ar comment
.Nm
.Op Fl D
.Fl r Ar path
.Sh DESCRIPTION
The
.Nm
utility runs
.Ox
regression tests.
The process is divided into the steps as follows:
.Bl -tag -width TESTS
.It env
Dump the current environment.
This is a no operation only used to collect data useful while debugging.
.It Ev TESTS
Run all configured regression tests synchronously, see
.Xr robsd-regress.conf 5 .
.It end
Auxillary step used to generate
.Pa report .
.El
.Pp
Each invocation is identified by a directory created by
.Nm
rooted in
.Ev ROBSDDIR
and is named after the current date.
The directory contains the entries as follows.
In addition, each regression test has a corresponding log file in the same
directory.
.Bl -tag -width robsd.log
.It Pa comment
File used to annotate the invocation which is included in
.Pa report .
.It Pa report
A summary delivered as a mail to root while running in detached mode once
.Nm
exits.
.It Pa robsd.log
Standard output and error from
.Nm
while running in detached mode.
.It Pa steps
Internal representation of the executed steps.
This file should never be edited manually.
.El
.Pp
.Nm
is configured using
.Xr robsd-regress.conf 5
and must be run as root.
Some steps can however operate on behalf of another user, see
.Xr robsd-regress.conf 5 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl D
Detach
.Nm
into the background.
.It Fl c Ar comment
Path to comment included in
.Pa report .
.It Fl r Ar path
Resume a run located at
.Ar path .
If the last regression test failed or aborted, it will be executed again.
Otherwise, the next regression test will be executed.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/robsd-regress.conf
The default configuration file.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr bsd.regress.mk 5 ,
.Xr robsd-regress.conf 5 ,
.Xr robsd 8 ,
.Xr robsd-regress-clean 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
