.Dd $Mdocdate: February 3 2022$
.Dt ROBSD-REGRESS.CONF 5
.Os
.Sh NAME
.Nm robsd-regress.conf
.Nd robsd-regress configuration file
.Sh DESCRIPTION
.Nm
is the configuration file for
.Xr robsd-regress 8 .
A string value type enclosed in
.Dq double-quotes
may refer to other configuration variables on the form
.No \(Do Ns Brq Ar variable .
Additional variables are also available, see
.Xr robsd-config 8 .
.Pp
The following variables are recognized:
.Bl -tag -width Ds
.It Ic robsddir Dq Ar path
Directory used to store invocations.
.It Ic hook No { Do Ar path Dc Ar ... No }
Command to invoke after each non-skipped step,
see
.Xr robsd-hook 5 .
.It Ic keep Ar number
Number of invocations to keep in
.Ic robsddir ,
see
.Xr robsd-regress-clean 8 .
Defaults to keeping everything.
.It Ic rdonly yes | no
Mount
.Ic bsd-srcdir
read-only before running any regression tests.
Used to detect object directory ignorance.
Requires
.Ic bsd-srcdir
to reside on a dedicated partition.
Defaults to
.Ic no .
.It Ic sudo Dq Ar command
Command used to elevate privileges, defaults to
.Dq doas -n .
.It Ic bsd-diff Dq Ar glob
Path to sticky patches to always apply to
.Ic bsd-srcdir ,
expressed as a
.Xr glob 7
pattern.
It's silently ignored if
.Ar glob
does not yield any matches.
.It Ic bsd-srcdir Dq Ar path
Source directory for the src tree, defaults to
.Pa /usr/src .
.It Ic cvs-user Dq Ar user
User to perform
.Xr patch 1
operations on behalf of.
.It Xo
.Ic regress Dq Ar path
.Op Ar options
.Xc
Regression test to execute where
.Ar path
must be relative to
.Pa ${bsd-srcdir}/regress .
May be given multiple times.
The following
.Ar options
can be used to influence the execution:
.Bl -tag -width Ds
.It Ic env No { Do Ar key=val Dc Ar ... No }
Add one more many environment variables.
.It Ic obj No { Ar path ... No }
Additional path requiring an object directory where path must be relative to
.Ic bsd-srcdir .
The object directory is created by the obj step, see
.Xr robsd-regress 8 .
.It Ic quiet
Do not report skipped or disabled targets for this regression test.
.It Ic root
Run the regression test as root as opposed of
.Ic regress-user .
.El
.It Ic regress-user Dq Ar user
User to run regression tests on behalf of.
.El
.Sh FILES
.Bl -tag -width "/etc/robsd-regress.conf"
.It Pa /etc/robsd-regress.conf
The default configuration file.
.El
.Sh EXAMPLES
Example configuration:
.Bd -literal
robsddir "/home/regress"
regress-user "anton"
regress "bin/csh"
regress "bin/ksh"
regress "sys/nfs" root
.Ed
.Sh SEE ALSO
.Xr robsd-config 8 ,
.Xr robsd-regress 8 ,
.Xr robsd-regress-clean 8 ,
.Xr robsd-regress-kill 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
