.Dd $Mdocdate: February 9 2022$
.Dt ROBSD-HOOK 5
.Os
.Sh NAME
.Nm robsd-hook
.Nd robsd hook configuration
.Sh DESCRIPTION
All robsd utilities can optionally execute a command after each non-skipped
step.
The command to execute is configured using the
.Ic hook
configuration variable and may contain one or many arguments passed to
.Xr execvp 3 .
For each argument, variables on the form
.Dq \(Do Ns Brq Ar variable
are interpolated where
.Ar variable
can refer to a configuration variable, see
.Xr robsd-config 8 .
In addition, the following variables are also available:
.Pp
.Bl -tag -compact -width step-exit
.It Ic step-exit
exit code of the step
.It Ic step-name
name of the step
.El
.Sh EXAMPLES
.Bd -literal
hook { "echo" "step ${step-name} done" }
.Ed
.Sh SEE ALSO
.Xr robsd-config 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
