.Dd $Mdocdate: September 24 2021$
.Dt ROBSD-PORTS 8
.Os
.Sh NAME
.Nm robsd-ports
.Nd build OpenBSD ports
.Sh SYNOPSIS
.Nm robsd-ports
.Op Fl D
.Op Fl c Ar comment
.Op Fl s Ar step
.Nm robsd-ports
.Op Fl D
.Fl r Ar path
.Sh DESCRIPTION
The
.Nm
utility builds
.Ox
ports.
The process is divided into the steps as follows:
.Bl -tag -width outdated
.It env
Dump the current environment.
This is a no operation only used to collect data useful while debugging.
.It cvs
Update the
.Ev PORTSDIR
source directory using the configured upstream, see
.Xr robsd-ports.conf 5 .
.It proot
Create the
.Ev CHROOT
using
.Xr proot 1 ,
this is where ports are built.
.It outdated
Determine which ports among the configured
.Ev PORTS
that must be built.
A port is considered outdated if the
.Ev PKGFILE
is absent or the package signature changed.
.It Ev PORTS
Build all outdated ports synchronously.
.It distrib
Distribute the packages for all configured
.Ev PORTS
including runtime dependencies to another host using
.Xr scp 1 .
If no outdated ports where detected, nothing is done.
This step is optional and requires presence of certain configuration, see
.Xr robsd-ports.conf 5 .
.It end
Auxillary step used to generate
.Pa report .
.El
.Pp
Each invocation is identified by a directory created by
.Nm
rooted in
.Ev ROBSDDIR
and is named after the current date.
The directory contains the entries as follows.
In addition, each port has a corresponding log file in the same directory.
.Bl -tag -width robsd.log
.It Pa comment
File used to annotate the invocation which is included in
.Pa report .
.It Pa report
A summary delivered as a mail to root while running in detached mode once
.Nm
exits.
.It Pa robsd.log
Standard output and error from
.Nm
while running in detached mode.
.It Pa steps
Internal representation of the executed steps.
This file should never be edited manually.
.El
.Pp
.Nm
is configured using
.Xr robsd-ports.conf 5
and must be run as root.
Some steps can however operate on behalf of another user.
Killing
.Nm
must be done using
.Xr robsd-ports-kill 8
to ensure a clean exit.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl D
Detach
.Nm
into the background.
.It Fl c Ar comment
Path to comment included in
.Pa report .
.It Fl r Ar path
Resume a ports build located at
.Ar path .
If the last port failed or aborted, it will be built again.
Otherwise, the next port will be built.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/robsd-ports.conf
The default configuration file.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr dpb 1 ,
.Xr proot 1 ,
.Xr robsd-ports.conf 5 ,
.Xr ports 7 ,
.Xr robsd 8 ,
.Xr robsd-ports-clean 8 ,
.Xr robsd-ports-kill 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
