.Dd $Mdocdate: October 7 2021$
.Dt ROBSD-KILL 8
.Os
.Sh NAME
.Nm robsd-kill
.Nd kill robsd
.Sh SYNOPSIS
.Nm robsd-kill
.Fl m Ar mode
.Sh DESCRIPTION
The
.Nm
utility
kills the corresponding robsd process in a graceful manner.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl m Ar mode
Mode used to indicate the kind of configuration.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
