.Dd $Mdocdate: October 14 2019$
.Dt ROBSD.CONF 5
.Os
.Sh NAME
.Nm robsd.conf ,
.Nm robsd-regress.conf
.Nd robsd configuration file
.Sh DESCRIPTION
The shell script
.Nm
is the configuration file for
.Xr robsd 8 .
By default,
.Xr robsd 8
is configured using environment variables.
Variables and can optionally be specified in
.Pa /etc/robsd.conf ,
which is sourced during runtime.
Where the latter takes higher precedence.
.Pp
The following variables are recognized.
Default values are displayed in brackets.
.Bl -tag -width Ds
.It Ev BSDDIFF
Path to sticky diff to always apply to the src tree.
The diff is ignored if the path does not exist.
May contain multiple paths separated by whitespace.
.It Ev BSDOBJDIR
Object directory for the src tree.
.Bq Pa /usr/obj
.It Ev BSDSRCDIR
Source directory for the src tree.
.Bq Pa /usr/src
.It Ev BUILDDIR
Directory to store releases.
.It Ev CVSROOT
Upstream
.Xr cvs 1
repository used to update sources from.
.It Ev CVSUSER
User to perform
.Xr cvs 1
and
.Xr patch 1
operations on behalf of.
.It Ev DESTDIR
Directory rooted on a filesystem mounted with the
.Em noperm
.Xr mount 8
option, see
.Xr release 8 .
.It Ev DISTRIBHOST
Host to upload the final release files to during the distribution step.
.It Ev DISTRIBPATH
Directory on
.Ev DISTRIBHOST
to upload the final release files to during the distribution step.
.It Ev DISTRIBUSER
User to perform
.Xr scp 1
operations on behalf of.
.It Ev HOOK
Command to invoke after each non-skipped step.
The command will be given the following arguments:
.Pp
.Bl -enum -compact
.It
Release build directory rooted in
.Ev BUILDDIR .
.It
Name of the step.
.It
Exit status of the step,
0 if the step succeeded and non-zero otherwise.
.El
.It Ev KEEP
Number of releases to keep in
.Ev BUILDDIR ,
see
.Xr robsd-clean 8 .
Defaults to keeping all releases.
.Bq 0
.It Ev MAKEFLAGS
Options passed to
.Xr make 1 .
Defaults to setting the maximum number of processes option to the value of
.Va hw.ncpuonline ,
see
.Xr sysctl 8 .
.It Ev SKIP
Steps to skip,
see
.Xr robsd-steps 8
for a list of all available steps.
May contain multiple steps separated by whitespace.
.It Ev SIGNIFY
Private key used to optionally sign the final release files using
.Xr signify 1 .
.It Ev XDIFF
Path to sticky diff to always apply to the xenocara tree.
The diff is ignored if the path does not exist.
May contain multiple paths separated by whitespace.
.It Ev XOBJDIR
Object directory for the xenocara tree.
.Bq /usr/xobj
.It Ev XSRCDIR
Source directory for the xenocara tree.
.Bq /usr/xenocara
.El
.Pp
In addition, the following variables are recognized by
.Xr robsd-regress 8 .
Default values are displayed in brackets.
.Bl -tag -width Ds
.It Ev NOTPARALLEL
Disable
.Xr make 1
parallelism for the given regression tests, separated by whitespace.
All entries must be relative to
.Pa ${BSDSRCDIR}/regress .
.It Ev REGRESSUSER
User to execute regression tests as.
.It Ev SUDO
Command used to elevate privilegies, needed by certain regression tests.
.Bq doas -n
.It Ev TESTS
Regression tests to execute, separated by whitespace.
All entries must be relative to
.Pa ${BSDSRCDIR}/regress .
.El
.Sh EXAMPLES
Example
.Pa /etc/robsd.conf
configuration file with all mandatory variables present:
.Bd -literal
BUILDDIR=/home/snapshots
CVSROOT=anoncvs@anoncvs.eu.openbsd.org:/cvs
CVSUSER=anton
DESTDIR=/home/noperm
.Ed
.Pp
Example
.Pa /etc/robsd-regress.conf
configuration file with all mandatory variables present:
.Bd -literal
BUILDDIR=/home/regress
REGRESSUSER=anton
TESTS="etc bin include lib libexec sbin sys usr.bin usr.sbin misc gnu"
.Ed
.Sh SEE ALSO
.Xr robsd 8 ,
.Xr robsd-clean 8 ,
.Xr robsd-regress 8 ,
.Xr robsd-rescue 8 ,
.Xr robsd-steps 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
