.Dd $Mdocdate: November 27 2018$
.Dt ROBSD 8
.Os
.Sh NAME
.Nm robsd
.Nd build OpenBSD release
.Sh SYNOPSIS
.Nm robsd
.Op Fl d
.Op Fl S Ar src-patch
.Op Fl X Ar xenocara-patch
.Op Fl c Ar comment
.Op Fl s Ar step
.Op Fl t Ar tag
.Nm
.Op Fl d
.Fl r Ar path
.Sh DESCRIPTION
The
.Nm
utility builds a
.Ox
release according to the
.Xr release 8
process.
The process is divided into the steps as follows:
.Bl -tag -width checkflist
.It env
Dump the current environment.
This is a no operation only used to collect data useful while debugging.
.It cvs
Update or checkout the
.Ic bsd-srcdir
and
.Ic x11-srcdir
source directories.
This step is optional and requires presence of certain configuration, see
.Xr robsd.conf 5 .
.It patch
Apply patches including sticky ones, see
.Xr robsd.conf 5 .
.It kernel
Build and install a new kernel using the
.Ic kernel
configuration, see
.Xr robsd.conf 5 .
.It reboot
Reboot the machine before continuing the build, exercising the new kernel by
resuming
.Nm
from
.Xr rc.firsttime 8 .
This step is optional and requires
.Ic reboot
to be enabled, see
.Xr robsd.conf 5 .
.It base
Build and install the base system.
.It release
Make and validate the base system.
.It checkflist
Check for missing contents in the release sets.
.It xbase
Build and install the xenocara system.
.It xrelease
Make and validate the xenocara system.
.It image
Create boot and installation disk images.
.It hash
Compute checksums for release files.
.It revert
Inverse of patch step.
.It distrib
Distribute the release files to another host using
.Xr scp 1 .
This step is optional and requires presence of certain configuration, see
.Xr robsd.conf 5 .
.It dmesg
Take a copy of
.Xr dmesg 8 .
.It end
Auxillary step used to generate
.Pa report .
.El
.Pp
Each invocation is identified by a directory created by
.Nm
rooted in
.Ic robsddir
and is named after the current date.
The directory contains the entries as follows.
In addition, each executed step has a corresponding log file in the same
directory.
.Bl -tag -width robsd.log
.It Pa comment
File used to annotate the invocation which is included in
.Pa report .
By default, it contains a list of all applied patches.
.It Pa dmesg
Copy of
.Xr dmesg 8 .
.It Pa rel
Directory containing the release files.
Referred to as RELEASEDIR in
.Xr release 8 .
.It Pa report
A summary delivered as a mail to root while running in the background once
.Nm
exits.
.It Pa robsd.log
Standard output and error from
.Nm
while running in the background.
.It Pa snapshots/$(machine)
Symlink to the
.Pa rel
directory, making the invocation directory compatible with
.Xr sysupgrade 8 .
.It Pa stat.csv
Collected statistics, see
.Xr robsd-stat 8 .
.It Pa step.csv
Internal representation of the executed steps, see
.Xr robsd-step 8 .
.It Pa tags
Tags included in
.Pa report .
.El
.Pp
.Nm
is configured using
.Xr robsd.conf 5
and must run as root.
Some steps can however operate on behalf of another user.
By default,
.Nm
runs in the background and must be killed using
.Xr robsd-kill 8
to ensure a clean exit.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Do not detach
.Nm
into the background.
.It Fl S Ar src-patch
Patch to apply to
.Ic bsd-srcdir .
The patch path names can be relative to any directory in
.Ic bsd-srcdir .
The same patch will be reverted by the revert step, see above.
In addition, a copy of the patch is saved to a file named
.Pa src.diff.N
in the invocation directory where N is incremented for every given patch.
May be given multiple times.
.It Fl X Ar xenocara-patch
Patch to apply to
.Ic x11-srcdir .
The patch path names can be relative to any directory in
.Ic x11-srcdir .
The same patch will be reverted by the revert step, see above.
In addition, a copy of the patch is saved to a file named
.Pa xenocara.diff.N
in the invocation directory where N is incremented for every given patch.
May be given multiple times.
.It Fl c Ar comment
Path to comment included in
.Pa report .
.It Fl r Ar path
Resume an invocation located at
.Ar path .
If the last executed step failed or aborted, it will be executed again.
Otherwise, the next step will be executed.
.It Fl s Ar step
Skip
.Ar step ,
see enumerated steps above.
May be given multiple times.
.It Fl t Ar tag
Arbitrary tag used to annotate the invocation which is included in
.Pa report .
May be given multiple times.
.El
.Sh FILES
.Bl -tag -width "/etc/robsd.conf"
.It Pa /etc/robsd.conf
The default configuration file.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr robsd.conf 5 ,
.Xr release 8 ,
.Xr robsd-clean 8 ,
.Xr robsd-cross 8 ,
.Xr robsd-kill 8 ,
.Xr robsd-ports 8 ,
.Xr robsd-regress 8 ,
.Xr robsd-rescue 8 ,
.Xr robsd-stat 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
