.Dd $Mdocdate: February 11 2021$
.Dt ROBSD-REGRESSS 8
.Os
.Sh NAME
.Nm robsd-regress
.Nd run OpenBSD regression tests
.Sh SYNOPSIS
.Nm robsd-regress
.Op Fl d
.Op Fl S Ar src-patch
.Op Fl c Ar comment
.Op Fl t Ar tag
.Nm
.Op Fl d
.Fl r Ar path
.Sh DESCRIPTION
The
.Nm
utility runs
.Ox
regression tests.
The process is divided into the steps as follows:
.Bl -tag -width regress
.It env
Dump the current environment.
This is a no operation only used to collect data useful while debugging.
.It cvs
Update the
.Ic bsd-srcdir
source directory.
This step is optional and requires presence of certain configuration, see
.Xr robsd-regress.conf 5 .
An initial checkout will be performed if the directory is empty.
.It patch
Apply patches including sticky ones, see
.Xr robsd-regress.conf 5 .
.It obj
Create object directories for all configured regression tests.
.It mount
Optionally mount
.Ic bsd-srcdir
read-only if
.Ic rdonly
is enabled, see
.Xr robsd-regress.conf 5 .
.It regress
Run all configured regression tests synchronously, see
.Xr robsd-regress.conf 5 .
.It umount
Inverse of mount step.
.It revert
Inverse of patch step.
.It end
Auxillary step used to generate
.Pa report .
.El
.Pp
Each invocation is identified by a directory created by
.Nm
rooted in
.Ic robsddir
and is named after the current date.
The directory contains the entries as follows.
In addition, each regression test has a corresponding log file in the same
directory.
.Bl -tag -width robsd.log
.It Pa comment
File used to annotate the invocation which is included in
.Pa report .
.It Pa stat.csv
Collected statistics, see
.Xr robsd-stat 8 .
.It Pa report
A summary delivered as a mail to root while running in the background once
.Nm
exits.
.It Pa robsd.log
Standard output and error from
.Nm
while running in the background.
.It Pa steps
Internal representation of the executed steps.
This file should never be edited manually.
.It Pa tags
Tags included in
.Pa report .
.El
.Pp
.Nm
is configured using
.Xr robsd-regress.conf 5
and must run as root.
Some steps can however operate on behalf of another user.
By default,
.Nm
runs in the background and must be killed using
.Xr robsd-regress-kill 8
to ensure a clean exit.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Do not detach
.Nm
into the background.
.It Fl S Ar src-patch
Patch to apply to
.Ic bsd-srcdir .
The patch path names can be relative to any directory in
.Ic bsd-srcdir .
The same patch will be reverted by the revert step, see above.
In addition, a copy of the patch is saved to a file named
.Pa src.diff.N
in the invocation directory where N is incremented for every given patch.
.It Fl c Ar comment
Path to comment included in
.Pa report .
.It Fl r Ar path
Resume an invocation located at
.Ar path .
If the last regression test failed or aborted, it will be executed again.
Otherwise, the next regression test will be executed.
.It Fl t Ar tag
Arbitrary tag used to annotate the invocation which is included in
.Pa report .
May be given multiple times.
.El
.Sh FILES
.Bl -tag -width /etc/robsd-regress.conf
.It Pa /etc/robsd-regress.conf
The default configuration file.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr bsd.regress.mk 5 ,
.Xr robsd-regress.conf 5 ,
.Xr robsd 8 ,
.Xr robsd-regress-clean 8 ,
.Xr robsd-regress-kill 8 ,
.Xr robsd-stat 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
