.Dd $Mdocdate: February 11 2021$
.Dt ROBSD-REGRESSS 8
.Os
.Sh NAME
.Nm robsd-regress
.Nd run OpenBSD regress suite
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/robsd.conf
The default configuration file.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr robsd.conf 5 ,
.Xr robsd 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
