#!/bin/ksh

set -eu

usage() {
	echo "usage: robsd-kill" 1>&2
	exit 1
}

. "${EXECDIR:-/usr/local/libexec/robsd}/util.sh"

[ $# -ne 0 ] && usage

setmode "$(getmode "$0")"
setprogname "${_MODE}-kill"
[ "$(id -u)" -ne 0 ] && fatal "must be run as root"
config_load "$(config_path)"

EXEC="${ROBSDEXEC:-/usr/local/libexec/robsd/${_MODE}-exec}"

[ -e "${ROBSDDIR}/.running" ] || fatal "${_MODE} is not running"
chflags uchg "${ROBSDDIR}/.running"
while pkill -f "^${EXEC}" 2>/dev/null; do
	sleep .1
done
