#!/bin/ksh

set -eu

usage() {
	xargs 1>&2 <<-EOF
	usage: robsd-crossenv target utility [argument ...]
	EOF
	exit 1
}

. "${EXECDIR:-/usr/local/libexec/robsd}/util.sh"

setmode "robsd-cross"
setprogname "robsd-cross"

[ $# -lt 2 ] && usage

_target="$1"; shift

config_load <<'EOF'
BSDSRCDIR="${bsd-srcdir}"
CROSSDIR="${crossdir}"
EOF

if ! [ -d "${CROSSDIR}${_target}" ]; then
	fatal "${CROSSDIR}${_target}: no such directory"
fi

_env="$(make -f "${BSDSRCDIR}/Makefile.cross" \
	"TARGET=${_target}" "CROSSDIR=${CROSSDIR}${_target}" cross-env)"
eval "export ${_env} BSDSRCDIR=${BSDSRCDIR}"
"$@"
