.Dd $Mdocdate: December 1 2021$
.Dt ROBSD-STAT 8
.Os
.Sh NAME
.Nm robsd-stat
.Nd statistics collector
.Sh SYNOPSIS
.Nm robsd-stat
.Sh DESCRIPTION
The
.Nm
utility collects statistics while
.Xr robsd 8 ,
.Xr robsd-ports 8
or
.Xr robsd-regress 8
is running.
It periodically outputs a line with comma separated values (CSV) using the
columns as follows:
.Bl -tag -width directory
.It time
The current time, expressed as the number of second since the Epoch.
.It load
The current load normalized with the number of CPUs.
.It user
Fraction of time spent in user space.
.It sys
Fraction of time spent in kernel space.
.It spin
Fraction of time spent spinning on locks.
.It intr
Fraction of time spent in interrupt context.
.It idle
Fraction of time doing nothing.
.It directory
Estimate of the current working directory for the corresponding robsd process.
Could be empty.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr robsd 8 ,
.Xr robsd-ports 8 ,
.Xr robsd-regress 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
