.Dd $Mdocdate: September 2 2020$
.Dt ROBSD-RESCUE 8
.Os
.Sh NAME
.Nm robsd-rescue
.Nd recover from failed robsd invocations
.Sh SYNOPSIS
.Nm robsd-rescue
.Fl m Ar mode
.Sh DESCRIPTION
The
.Nm
utility tries to recover from the last corresponding robsd invocation by
performing the actions as follows:
.Bl -dash
.It
Reverting any diff applied to the source directories.
.It
Release the lock, allowing for new invocations.
.El
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl m Ar mode
Mode used to indicate the kind of configuration.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
