#!/bin/ksh

set -eu

usage() {
	xargs 1>&2 <<-EOF
	usage: robsd-regress
	[-D]
	[-c comment]
	[-r path]
	EOF
	exit 1
}

. "${EXECDIR:-/usr/local/libexec/robsd}/util.sh"

setmode "robsd-regress"
setprogname "robsd-regress"
[ "$(id -u)" -ne 0 ] && fatal "must be run as root"
config_load "$(config_path)"

COMMENT=""
STEP=1

while getopts "Dc:r:" opt; do
	case "$opt" in
	D)	DETACH=1;;
	c)	COMMENT="$OPTARG";;
	r)	BUILDDIR="$(readlink -f "$OPTARG")";;
	*)	usage;;
	esac
done
shift $((OPTIND - 1))
[ $# -ne 0 ] && usage

trap 'trap_exit -r "$ROBSDDIR" -b "$BUILDDIR"' EXIT

if [ -z "$BUILDDIR" ]; then
	check_perf || exit 1

	BUILDDIR="${ROBSDDIR}/$(build_id "$ROBSDDIR")"
else
	STEP="$(step_next "${BUILDDIR}/steps")"
fi
build_init "$BUILDDIR"
info "using directory ${BUILDDIR} at step ${STEP}"

lock_acquire "$ROBSDDIR" "$BUILDDIR" || exit 1

if [ "$STEP" -eq 1 ]; then
	if [ -n "$COMMENT" ]; then
		cat "$COMMENT" >"${BUILDDIR}/comment"
	fi
fi

if [ "$KEEP" -gt 0 ]; then
	/usr/local/sbin/robsd-regress-clean "$KEEP"
fi

if [ "$DETACH" -eq 1 ]; then
	# Signal to info() that no further output should be written to robsd.log
	# as we're about redirect all output to the same log.
	DETACH=2
	exec </dev/null >>"${BUILDDIR}/robsd.log" 2>&1

	# Reinstall trap handler since they are not inherited by subprocesses.
	trap '-' EXIT
	{
		trap 'trap_exit -r "$ROBSDDIR" -b "$BUILDDIR"' EXIT
		robsd "$STEP"
	} &
	info "running in detach mode as pid ${!}"
else
	info "running as pid ${$}"
	robsd "$STEP"
fi
