.Dd $Mdocdate: October 14 2019$
.Dt ROBSD-CLEAN 8
.Os
.Sh NAME
.Nm robsd-clean
.Nd clean old invocations
.Sh SYNOPSIS
.Nm robsd-clean
.Fl m Ar mode
.Ar count
.Sh DESCRIPTION
The
.Nm
utility cleans out old invocations,
keeping only the
.Ar count
number of latest ones.
.Pp
Old invocations are moved to a directory named
.Pa attic
rooted in
.Ic robsddir .
Only a selected few files are kept in order to reduce disk usage.
The same files can be used to track various metrics over time.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl m Ar mode
Mode used to indicate the kind of configuration.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
