.Dd $Mdocdate: November 27 2018$
.Dt ROBSD 8
.Os
.Sh NAME
.Nm robsd
.Nd build OpenBSD release
.Sh SYNOPSIS
.Nm robsd
.Op Fl v
.Op Fl c Ar file
.Op Fl S Ar src-diff
.Op Fl X Ar xenocara-diff
.Nm
.Op Fl v
.Fl r Ar path
.Sh DESCRIPTION
The
.Nm
utility builds a
.Ox
release according to the
.Xr release 8
process.
Some steps are enhanced as follows:
.Bl -dash
.It
During step 2
.Pq Build and install a new kernel
the
.Pa GENERIC.MP
kernel is favored on multiprocessor machines based on
.Va hw.ncpu ,
see
.Xr sysctl 8 .
Otherwise,
the
.Pa GENERIC
kernel is used.
.El
.Pp
In addition, the following steps are also executed:
.Bl -dash
.It
After step 2
.Pq Build and install a new kernel
the machine is rebooted.
Upon the next boot, the same release build is resumed from
.Xr rc.firsttime 8 .
.It
After step 8
.Pq Create boot and installation disk images
the final release files are distributed to another host using
.Xr scp 1 .
.El
.Pp
Each release build is identified by a directory created by
.Nm
rooted in
.Ev BUILDDIR
and named after the current date.
The release directory contains the entries as follows.
In addition, each executed step has a corresponding log file in the same
directory.
.Bl -tag -width Ds
.It Pa comment
File used to annotate the release build.
.It Pa reldir
Directory containing the final release files.
Referred to as RELEASEDIR in
.Xr release 8 .
.It Pa report
A summary of the release build which is delivered as a mail to root once
.Nm
exits.
.It Pa steps
Internal representation of the executed steps.
This file should never be edited manually.
.El
.Pp
.Nm
is configured using
.Xr robsdrc 5
and must be run as root.
Some steps can however operate on behalf of another user using
.Xr su 1 ,
see
.Xr robsdrc 5 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar file
Annotate the release build.
.Ar file
is copied to
.Pa comment
in the release directory.
If
.Ar file
is
.Sq - ,
stdin is used.
.It Fl r Ar path
Resume a release build located at
.Ar path .
If the last executed step failed, it will be executed again.
Otherwise, the next step will be executed.
.It Fl S Ar src-diff
Diff to apply to the src tree.
The same diff will be reverted once the release is finished.
In addition, a copy of the diff is saved to a file named
.Pa src.diff
in the release directory.
.It Fl v
Enable verbose output.
.It Fl X Ar xenocara-diff
Diff to apply to the xenocara tree.
The same diff will be reverted once the release is finished.
In addition, a copy of the diff is saved to a file named
.Pa xenocara.diff
in the release directory.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/robsdrc
The default configuration file.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr robsdrc 5 ,
.Xr release 8 ,
.Xr robsd-clean 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
