.Dd $Mdocdate: October 7 2021$
.Dt ROBSD-KILL 8
.Os
.Sh NAME
.Nm robsd-kill ,
.Nm robsd-cross-kill ,
.Nm robsd-ports-kill ,
.Nm robsd-regress-kill
.Nd kill robsd
.Sh SYNOPSIS
.Nm robsd-kill
.Nm robsd-cross-kill
.Nm robsd-ports-kill
.Nm robsd-regress-kill
.Sh DESCRIPTION
The
.Nm
utility
kills the corresponding robsd utility in a graceful manner.
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr robsd.conf 5 ,
.Xr robsd 8 ,
.Xr robsd-ports 8 ,
.Xr robsd-regress 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
