#!/bin/ksh

set -eu

usage() {
	xargs 1>&2 <<-EOF
	usage: robsd-crossenv target utility [argument ...]
	EOF
	exit 1
}

. "${EXECDIR:-/usr/local/libexec/robsd}/util.sh"

setmode "robsd-cross"
setprogname "robsd-cross"

[ $# -lt 2 ] && usage

_target="$1"; shift

config_load -v "target=${_target}" <<'EOF'
BSDSRCDIR="${bsd-srcdir}"
CROSSDIR="${crossdir}"
EOF

if ! [ -d "$CROSSDIR" ]; then
	fatal "${CROSSDIR}: no such directory"
fi

_env="$(cross_env "$BSDSRCDIR" "$CROSSDIR" "$_target")"
eval "export ${_env} BSDSRCDIR=${BSDSRCDIR}"
"$@"
