#!/bin/ksh

set -eu

usage() {
	echo "usage: robsd-steps" 1>&2
	exit 1
}

. "${EXECDIR:-/usr/local/libexec/robsd}/util.sh"

[ $# -ne 0 ] && usage

setprogname "robsd-steps"
# No root privileges required.
config_load "${ROBSDCONF:-/etc/robsd.conf}"

step_names | grep -vw -e env -e end
