.Dd $Mdocdate: September 9 2020$
.Dt ROBSD-STEPS 8
.Os
.Sh NAME
.Nm robsd-steps
.Nd list all release steps
.Sh SYNOPSIS
.Nm robsd-steps
.Sh DESCRIPTION
The
.Nm
utility lists all release steps performed by
.Xr robsd 8 .
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/robsdrc
The default configuration file.
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr robsdrc 5 ,
.Xr robsd 8
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
