name: test

on:
  - push
  - pull_request

jobs:
  linux-gcc-sanitize:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install libxml2-utils
      - name: test
        env:
          CC: gcc
          PORTABLE: yes
        run: |
          ./configure --pedantic --sanitize
          make -j`nproc` test

  linux-gcc-i386:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install gcc-multilib libxml2-utils
      - name: test
        env:
          CC: gcc
          CFLAGS: -m32
          LDFLAGS: -m32
          PORTABLE: yes
        run: |
          ./configure --pedantic
          make -j`nproc` test

  linux-gcc-4:
    runs-on: ubuntu-22.04
    container: ghcr.io/mptre/gcc:4
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: gcc
          CFLAGS: -Werror
        run: |
          # Only compile and skip pedantic due to compiler being ancient.
          ./configure
          make -j`nproc`

  linux-clang-sanitize:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install libxml2-utils
      - name: test
        env:
          CC: clang
          PORTABLE: yes
        run: |
          ./configure --pedantic --sanitize
          make -j`nproc` test

  valgrind:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install libxml2-utils valgrind
      - name: test
        env:
          CC: gcc
          EXEC: valgrind
          PORTABLE: yes
          TESTFLAGS: -Tmemleak
          VALGRIND_OPTS: --quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all
        run: |
          ./configure --pedantic
          make -j`nproc` test

  ndebug:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install libxml2-utils
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DNDEBUG
          PORTABLE: yes
        run: |
          ./configure --pedantic
          make -j`nproc` test

  fuzz:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install afl
      - name: test
        env:
          CC: afl-gcc
        run: |
          ./configure --pedantic --fuzz afl
          make -j`nproc` fuzz

  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clang-tidy
        run: |
          ./configure --pedantic
          make lint-clang-tidy

  cppcheck:
    runs-on: ubuntu-22.04
    container: ghcr.io/mptre/cppcheck:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cppcheck
        run: |
          ./configure --pedantic
          make lint-cppcheck
